#!/usr/bin/env bash
# Builds a fake dataset so the dashboard can be shown, photographed or tried out
# with no real repos and nobody's real names in it.
#
#   bash demo/make-demo.sh          builds demo/data and prints how to run it
#
# The bundle files are sparse: they report a realistic size and use almost no disk.
# An older demo/data is moved aside with a timestamp, never removed. Delete the
# old folders yourself when you are sure you do not want them.
set -u
: "${GDB_PYTHON:=$(command -v python3 || command -v python)}"   # before config.sh is sourced
ROOT="${0:A:h:h}"
D="$ROOT/demo/data"
if [ -d "$D" ]; then
  OLD="$D-$(date +%Y%m%d-%H%M%S)"
  mv "$D" "$OLD"
  echo "moved the previous demo data to $OLD"
fi
mkdir -p "$D"/{state,logs,proofs,mirrors,dashboard/tests} "$D"/cloud/{full,inc,archive,metadata}
"$GDB_PYTHON" "$ROOT/demo/make-demo.py" "$D"
cat > "$ROOT/demo/config.env" <<CONF
# Generated by demo/make-demo.sh. Fake data, safe to move aside.
CLOUD_DIR="$D/cloud"
DATA_DIR="$D"
DASH_PORT=3091
LABEL_PREFIX="com.gitdrivebackup.demo"
CONF
echo
echo "Demo data built. Start the demo dashboard with:"
echo "  GDB_CONFIG=$ROOT/demo/config.env $GDB_PYTHON $ROOT/bin/dashboard.py"
echo "Then open http://localhost:3091"
